### ISSUE TITLE
Download zkey shows no progress

### ISSUE THREAD

**Issue by numtel** [privacy-scaling-explorations/DefinitelySetup#117]
**Describe the bug**
After clicking to download a zkey, there is no progress reported during the download. This can be a while for the larger files like the 4.5GB zkp2p zkeys. By the time it finished, I had used the dev tools to extract the url and download it manually and the original click download finished a few seconds before my intervention.

**To Reproduce**
1. Go to ['ZKp2p trusted setup...'](https://ceremony.pse.dev/projects/ZKP2P%20Trusted%20Setup%20Ceremony%20V2.4)
2. Click on Download venmo-send-v2_final
3. Wait for a long time
4. Download appears and completes instantly

**Expected behavior**
The download should begin at the moment of clicking instead of instantly appearing after the entire file completes.

**Desktop:**
 - OS: fedora 40
 - Browser firefox + chrome

**Additional context**
Relevant code here: https://github.com/privacy-scaling-explorations/DefinitelySetup/blob/8605425a0faf98da7ffe513beacb6794e8324436/web/src/pages/ProjectPage.tsx#L143

**Comment by glamperd** [comment]
Merged into prod
