### ISSUE TITLE
Request to Start Grant Process to Cover Infrastrcture Costs -- EmailApprover

### ISSUE THREAD

**Issue by jayden-sudo** [privacy-scaling-explorations/DefinitelySetup#122]
Firstly, I would like to thank the PSE team for providing such excellent tools.

EmailApprover is based on [zkemail](https://github.com/zkemail/zk-email-verify) and is currently used to set email guardians for users. Due to the circuit's constraint size being over 1M (actual size: 2,163,550), we are requesting to start a grant process to cover the infrastructure costs. 

Project repository: [Link](https://github.com/SoulWallet/email-approver/blob/main/packages/circuits/EmailApprover.circom).

**Comment by glamperd** [comment]
Hi, I don't see any licensing info in your repo. It appears to be open source, but an explicit OS license would be better.

**Comment by jayden-sudo** [comment]
> Hi, I don't see any licensing info in your repo. It appears to be open source, but an explicit OS license would be better.

Thank you for pointing out the issue. I have just added the license file.

**Comment by glamperd** [comment]
We've had a discussion about this request. For various reasons, we'd prefer if you set up your own infrastructure to run the trusted setup with. We're happy to help guide you through the process. 
Get in touch to discuss this further. One way to do that is to join the p0tion Discord channel, here: https://discord.com/channels/943612659163602974/1164313923357519892
