### ISSUE TITLE
Error verifying, FirebaseError: internal

### ISSUE THREAD

**Issue by alxkzmn** [privacy-scaling-explorations/DefinitelySetup#85]
**Describe the bug**
Error verifying, FirebaseError: internal displayed after some time after resuming the contribution 

**To Reproduce**
Start a contribution - get a timeout - reopen the page and start the contribution again. In my case I did that twice after getting a timeout twice (and also switching between ceremonies). Cannot specify the exact sequence, but if I remember correctly, first started the RLN ceremony, it timed out, then retried it, it timed out again, then switched to MACI, later it timed out, then switched to RLN again and got the error.

**Expected behavior**
Not showing the error.

**Screenshots**
![image](https://github.com/privacy-scaling-explorations/DefinitelySetup/assets/6849426/34543c5b-99fa-46f4-bf89-809bb8213085)

**Desktop (please complete the following information):**
 - OSX 13.5
 - Firefox 116.0.2

**Comment by ctrlc03** [comment]
Thanks for reporting this, I fixed it here https://github.com/privacy-scaling-explorations/DefinitelySetup/pull/87 - please try again when you get a chance.
